spring:
  application:
    name: zuul-server
server:
  port: 8087
eureka:
  instance:
    hostname: zuul-server
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    eureka-client-1:
      path: /client/**
      serviceId: eureka-client-1
