##设置服务基础配置
spring:
  application:
    name: eureka-server-1
---
spring:
  profiles: peer1
server:
  port: 8761
  ##注册中心相关配置
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: false  #由于本服务是注册中心 所以设置不向注册中心注册自己
    fetch-registry: false #由于注册中心的职责就是维护实例，所以它不需要去检索实例
---
spring:
  profiles: peer2
server:
  port: 8762
  ##注册中心相关配置
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

