

server:
  port: 8089

spring:
  application:
    name: sun-rain-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#eureka:
#  client:
#    service-url:
#      zone1: http://localhost:8762/eureka/
#      zone2: http://localhost:8761/eureka/
#  instance:
#    hostname: sun-rain-cloud-gateway
#    #表示将自己的ip注册到eureka server  如不配置该属性或者将其设置为false
#    #则表示注册微服务所在hostname 注册到eureka server 上
#    prefer-ip-address: true

